// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ooP6vK2zf5p9dGzVtPkRCaJHN7FBsEU',
    appId: '1:548853804763:web:5f383af1e2c6af4607e6fe',
    messagingSenderId: '548853804763',
    projectId: 'fir-series-79998',
    authDomain: 'fir-series-79998.firebaseapp.com',
    storageBucket: 'fir-series-79998.appspot.com',
    measurementId: 'G-MSDZDPK6GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5j0zOOPJnCnh8GEwPGhAW1pJ-v49qChw',
    appId: '1:548853804763:android:f3fac932e612b48a07e6fe',
    messagingSenderId: '548853804763',
    projectId: 'fir-series-79998',
    storageBucket: 'fir-series-79998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiOYpeiwgpjBNI2aeRoDpxn7_tdrBxJwo',
    appId: '1:548853804763:ios:d95903d3f792dc1107e6fe',
    messagingSenderId: '548853804763',
    projectId: 'fir-series-79998',
    storageBucket: 'fir-series-79998.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiOYpeiwgpjBNI2aeRoDpxn7_tdrBxJwo',
    appId: '1:548853804763:ios:f769f9c553baf69e07e6fe',
    messagingSenderId: '548853804763',
    projectId: 'fir-series-79998',
    storageBucket: 'fir-series-79998.appspot.com',
    iosBundleId: 'com.example.firebaseSeries.RunnerTests',
  );
}
